name: MusicStoryRenderer

options:
  bundleIdPrefix: net.bomash.illya
  postGenCommand: python3 ../../scripts/fix_iconcomposer_filetype.py

configFiles:
  Debug: Config/Signing.xcconfig
  Release: Config/Signing.xcconfig

targets:
  MusicStoryRendererCore:
    type: framework
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Models
      - StoryParser.swift
      - StoryPackageLoader.swift
    settings:
      base:
        SWIFT_VERSION: 6.2
        GENERATE_INFOPLIST_FILE: YES

  MusicStoryRenderer:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: App
      - path: Models
      - path: Playback
      - path: Rendering
      - StoryParser.swift
      - StoryPackageLoader.swift
      - StoryDocumentStore.swift
      - StoryPersistence.swift
      - path: ../app-icon/MusicStories-AppIcon-Composed.icon
        buildPhase: resources
    resources:
      - path: ../../stories
        type: folder
    postBuildScripts:
      - name: Bundle Stories
        script: |
          set -euo pipefail
          SOURCE_DIR="${SRCROOT}/../../stories"
          DEST_DIR="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/stories"
          if [ -d "${SOURCE_DIR}" ]; then
            rm -rf "${DEST_DIR}"
            mkdir -p "${DEST_DIR}"
            rsync -a --delete "${SOURCE_DIR}/" "${DEST_DIR}/"
          fi
    settings:
      base:
        SWIFT_VERSION: 6.2
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: net.bomash.illya.MusicStories
        CODE_SIGN_ENTITLEMENTS: App/MusicStoryRenderer.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: MusicStories-AppIcon-Composed

  MusicStoryRendererCoreTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Tests/MusicStoryRendererCoreTests
    settings:
      base:
        SWIFT_VERSION: 6.2
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: MusicStoryRendererCore

  MusicStoryRendererTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: Tests/MusicStoryRendererTests
    settings:
      base:
        SWIFT_VERSION: 6.2
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: MusicStoryRenderer

schemes:
  MusicStoryRenderer:
    build:
      targets:
        MusicStoryRenderer: all
    test:
      targets:
        - MusicStoryRendererCoreTests
        - MusicStoryRendererTests
